/**
 * Build-time entrypoint: emit the v4 app bundle at `dist/atlas-app/`.
 *
 *   - `dist/atlas-app/index.html`        — single-page shell
 *   - `dist/atlas-app/app.js`            — bundled vanilla TS app
 *   - `dist/atlas-app/seed.json`         — section/family/card payload
 *
 * The seed is generated by reusing the same renderers `pnpm build:atlas`
 * uses (`renderPrimitive` / `renderPrimitiveBack`) so the look of the
 * cards is byte-for-byte the same as the v3 static archive. The app
 * mounts the SVGs into the card frame at runtime.
 *
 * Run: pnpm build:atlas-app
 *
 * Coexists with build:atlas — both can run, neither overwrites the
 * other's output directory.
 */

import { execSync } from 'node:child_process'
import { mkdir, readFile, writeFile, cp, rm } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

import { build as viteBuild } from 'vite'

import type { Primitive, PrimitiveFamily } from '../src/atlas/types.js'
import { renderPrimitive, renderPrimitiveBack } from '../src/atlas/render/index.js'
import type { BackRenderContext, RenderContext } from '../src/atlas/render/types.js'
import { renderFamilyKeyCard } from '../src/atlas/render/key-card.js'
import { resolveSourceCitation } from '../src/atlas/render/back-helpers.js'
import type { SectionsFile, GlossaryFile } from '../src/atlas/render/gallery.js'
import type { AppSeed, AppCard, AppAct, AppFamilySection } from '../src/atlas-app/seed.js'
import { resolveSpectralLineAnimation } from '../src/atlas-app/resolve-transition.js'
import { ROOT, loadAtlasSeeds } from './atlas-seeds.js'

const SCHEMA_VERSION = '4.0-alpha'
const OUT_DIR = resolve(ROOT, 'dist/atlas-app')
const DATA_DIR = resolve(ROOT, 'src/atlas/data')

async function readOptionalJson<T>(path: string, label: string): Promise<T | undefined> {
  try {
    const raw = await readFile(path, 'utf-8')
    return JSON.parse(raw) as T
  } catch (err: unknown) {
    const code = (err as { code?: string }).code
    if (code === 'ENOENT') {
      console.warn(`[atlas-app] ${label} not found at ${path}; falling back.`)
      return undefined
    }
    console.warn(
      `[atlas-app] ${label} could not be parsed (${(err as Error).message}); using fallback.`,
    )
    return undefined
  }
}

function readGitRev(): string {
  try {
    return execSync('git rev-parse --short HEAD', {
      cwd: ROOT,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim()
  } catch {
    return 'unknown'
  }
}

async function buildSeed(): Promise<AppSeed> {
  const { sources, primitives } = await loadAtlasSeeds()
  const ctx: RenderContext = { sources }

  const primitivesById = new Map<string, Primitive>()
  for (const p of primitives) primitivesById.set(p.id, p)

  const backCtx: BackRenderContext = { sources, primitives: primitivesById }

  // Fold every primitive into a card record with inlined SVG.
  const cards: Record<string, AppCard> = {}
  for (const p of primitivesById.values()) {
    const front = renderPrimitive(p, ctx)
    const back = renderPrimitiveBack(p, backCtx)
    const source = sources.get(p.sourceId)
    const animation = resolveSpectralLineAnimation(p, primitivesById)
    cards[p.id] = {
      id: p.id,
      family: p.family,
      name: p.name,
      symbol: p.symbol,
      frontSvg: front.svg,
      backSvg: back.svg,
      sectionNumber: 0, // filled in below once we walk sections
      actNumber: 0,
      sourceLabel: source?.citation ?? resolveSourceCitation(p.sourceId),
      retrievedAt: p.retrievedAt,
      ...(animation ? { animation } : {}),
    }
  }

  // Authored content.
  const sections = await readOptionalJson<SectionsFile>(
    resolve(DATA_DIR, 'sections.json'),
    'sections.json',
  )
  const glossary = await readOptionalJson<GlossaryFile>(
    resolve(DATA_DIR, 'glossary.json'),
    'glossary.json',
  )
  void glossary // glossary tooltips arrive in v4-β; cards still render fine without them.

  // Build the ordered act → family → card list. If sections.json is
  // absent we group by family using the v3 fallback order.
  const familyMembers = new Map<PrimitiveFamily, string[]>()
  for (const p of primitivesById.values()) {
    if (!familyMembers.has(p.family)) familyMembers.set(p.family, [])
    familyMembers.get(p.family)!.push(p.id)
  }

  const acts: AppAct[] = []
  if (sections?.acts?.length) {
    for (const act of sections.acts) {
      const families: AppFamilySection[] = []
      for (const fs of act.families ?? []) {
        const all = familyMembers.get(fs.family) ?? []
        if (all.length === 0) continue
        // Order: explicit primitiveOrder first, then alphabetical for the rest.
        const explicit = fs.primitiveOrder ?? []
        const explicitSet = new Set(explicit)
        const rest = all.filter((id) => !explicitSet.has(id)).sort()
        const ordered = [
          ...explicit.filter((id) => primitivesById.has(id)),
          // The KEY-CARD synthetic id is injected below.
          ...rest,
        ]
        // Inject the family key card as the first member of every family.
        const keyId = `_key.${fs.family}`
        const keyExisting = cards[keyId]
        if (!keyExisting) {
          const { frontSvg, backSvg } = renderFamilyKeyCard(fs.family, { count: all.length })
          cards[keyId] = {
            id: keyId,
            family: fs.family,
            name: fs.title,
            symbol: '◇ key',
            frontSvg,
            backSvg,
            sectionNumber: fs.sectionNumber,
            actNumber: act.actNumber,
            sourceLabel: 'family key card',
            retrievedAt: undefined,
          }
        }
        const cardIds = [keyId, ...ordered]
        // Stamp section/act on every card we just enumerated.
        for (const cid of cardIds) {
          const c = cards[cid]
          if (c) {
            c.sectionNumber = fs.sectionNumber
            c.actNumber = act.actNumber
          }
        }
        families.push({
          family: fs.family,
          sectionNumber: fs.sectionNumber,
          title: fs.title,
          intro: fs.intro,
          cardIds,
        })
      }
      if (families.length > 0) {
        acts.push({
          actNumber: act.actNumber,
          title: act.title,
          subtitle: act.subtitle,
          intro: act.intro,
          families,
        })
      }
    }
  } else {
    // Fallback: one synthetic act, families in v3 fallback order.
    const FALLBACK: PrimitiveFamily[] = [
      'constant',
      'unit',
      'identity',
      'special-function',
      'spectral-line',
      'energy-level',
      'element',
      'series',
      'transition-type',
      'polytope',
      'coord-system',
      'lattice',
      'tiling',
      'curved-space',
      'symmetry-group',
    ]
    const families: AppFamilySection[] = []
    let sectionNumber = 0
    for (const family of FALLBACK) {
      const ids = familyMembers.get(family)
      if (!ids || ids.length === 0) continue
      sectionNumber += 1
      const keyId = `_key.${family}`
      const { frontSvg, backSvg } = renderFamilyKeyCard(family, { count: ids.length })
      cards[keyId] = {
        id: keyId,
        family,
        name: family,
        symbol: '◇ key',
        frontSvg,
        backSvg,
        sectionNumber,
        actNumber: 1,
        sourceLabel: 'family key card',
        retrievedAt: undefined,
      }
      const cardIds = [keyId, ...ids.sort()]
      for (const cid of cardIds) {
        const c = cards[cid]
        if (c) {
          c.sectionNumber = sectionNumber
          c.actNumber = 1
        }
      }
      families.push({
        family,
        sectionNumber,
        title: family,
        intro: '',
        cardIds,
      })
    }
    acts.push({
      actNumber: 1,
      title: 'Atlas',
      subtitle: '',
      intro: '',
      families,
    })
  }

  return {
    schemaVersion: SCHEMA_VERSION,
    generatedAt: new Date().toISOString().replace('T', ' ').replace(/\..+$/, ' UTC'),
    gitRev: readGitRev(),
    title: sections?.title ?? 'linelight atlas',
    subtitle: sections?.subtitle ?? '',
    intro: sections?.intro ?? '',
    closing: sections?.closing,
    acts,
    cards,
  }
}

const HTML_SHELL = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>linelight atlas — v4</title>
<link rel="stylesheet" href="app.css" />
</head>
<body>
<div id="root"></div>
<script type="module" src="app.js"></script>
</body>
</html>
`

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true })

  console.log('[atlas-app] generating seed.json…')
  const seed = await buildSeed()
  await writeFile(resolve(OUT_DIR, 'seed.json'), JSON.stringify(seed))

  console.log('[atlas-app] writing index.html shell…')
  await writeFile(resolve(OUT_DIR, 'index.html'), HTML_SHELL)

  console.log('[atlas-app] bundling app.js via vite…')
  // Build the app bundle. We use Vite in library-ish mode (single entry
  // → ESM output) and let it tree-shake. Output goes to a temp dir so
  // we can selectively copy app.js + app.css over.
  const tmpDir = resolve(ROOT, 'dist/.atlas-app-build')
  if (existsSync(tmpDir)) await rm(tmpDir, { recursive: true, force: true })
  await viteBuild({
    root: ROOT,
    configFile: false,
    logLevel: 'warn',
    base: './',
    build: {
      outDir: tmpDir,
      emptyOutDir: true,
      target: 'es2022',
      cssCodeSplit: false,
      sourcemap: false,
      rollupOptions: {
        input: resolve(ROOT, 'src/atlas-app/main.ts'),
        output: {
          entryFileNames: 'app.js',
          chunkFileNames: 'app-[hash].js',
          assetFileNames: (asset) => {
            if (asset.name && asset.name.endsWith('.css')) return 'app.css'
            return 'asset-[hash][extname]'
          },
        },
      },
    },
  })

  // Copy the bundled artifacts into OUT_DIR.
  const fsCopy = async (rel: string) => {
    const src = resolve(tmpDir, rel)
    if (existsSync(src)) await cp(src, resolve(OUT_DIR, rel), { recursive: false })
  }
  await fsCopy('app.js')
  await fsCopy('app.css')

  // Surface chunk files too in case Vite splits.
  const lsRoot = resolve(tmpDir)
  if (existsSync(lsRoot)) {
    const { readdir, stat } = await import('node:fs/promises')
    const entries = await readdir(lsRoot)
    for (const e of entries) {
      if (e === 'app.js' || e === 'app.css') continue
      const fullSrc = resolve(lsRoot, e)
      const st = await stat(fullSrc)
      if (st.isFile() && /\.(js|css)$/.test(e)) {
        await cp(fullSrc, resolve(OUT_DIR, e))
      }
    }
  }

  // Drop a manifest line for parity with the v3 build.
  const manifest = {
    schema_version: SCHEMA_VERSION,
    git_rev: seed.gitRev,
    built_at: new Date().toISOString(),
    cards_total: Object.keys(seed.cards).length,
    acts_total: seed.acts.length,
  }
  await writeFile(resolve(OUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n')

  // Best-effort cleanup; keep tmpDir around if removal fails.
  try {
    await rm(tmpDir, { recursive: true, force: true })
  } catch {
    /* ignore */
  }

  console.log(
    `[atlas-app] wrote ${Object.keys(seed.cards).length} cards across ${seed.acts.length} acts`,
  )
  console.log(`[atlas-app] output: ${OUT_DIR}`)

  // Suppress unused-import warning for `dirname` if the cleanup branch
  // above was tree-shaken in a future refactor.
  void dirname
}

main().catch((err) => {
  console.error('[atlas-app] build failed:', err)
  process.exit(1)
})
